export const topics = {
  intro: [
    'go-introduction',
    'compiling',
    'compiled-vs-interpreted',
    'go-memory-usage',
    'go-is-strongly-typed',
    'requirements',
    'wrapping-up',
  ],
  setting_up_environment: [
    'installing-go-tools',
    'packages',
    'modules',
    'your-first-go-program',
    'go-tooling',
    'choose-your-tools',
    'wrapping-up',
  ],
  variables_and_types: [
    'basic-types',
    'type-inference',
    'type-sizes',
    'constants',
    'formatting-strings',
    'conditionals',
    'wrapping-up',
  ],
  functions: [
    'intro',
    'declaration-syntax',
    'return-values',
    'named-returns',
    'benefits-of-named-returns',
    'early-returns',
    'wrapping-up',
  ],
  structs: [
    'structs-in-go',
    'nested-structs',
    'anonymous-structs',
    'embedded-structs',
    'struct-methods',
    'wrapping-up',
  ],
  interfaces: [
    'interfaces-in-go',
    'multiple-interfaces',
    'type-assertion',
    'clean-interfaces',
    'wrapping-up',
  ],
  errors: [
    'the-error-interface',
    'formatting-strings',
    'custom-errors',
    'the-errors-package',
    'wrapping-up',
  ],
  loops: [
    'intro',
    'omitting-conditions',
    'while-loop',
    'operators',
    'continue-and-break',
    'wrapping-up',
  ],
  slices: [
    'arrays',
    'slices-in-go',
    'slices-review',
    'make-function',
    'len-and-cap-review',
    'variadic-functions',
    'slice-gotcha',
    'wrapping-up',
  ],
  maps: [
    'maps-in-go',
    'mutating-maps',
    'key-types',
    'nested-maps',
    'maps-review',
    'wrapping-up',
  ],
  advanced_functions: [
    'higher-order-functions',
    'why-higher-order-functions',
    'currying',
    'defer',
    'closures',
    'anonymous-functions',
    'pointers-intro',
    'pointer-receivers',
    'wrapping-up',
  ],
  channels: [
    'concurrency',
    'channels-in-go',
    'closing-channels',
    'select-statement',
    'select-default-case',
    'channels-review',
    'wrapping-up',
  ],
  mutexes_and_generics: [
    'mutexes-in-go',
    'more-on-mutexes',
    'rw-mutex',
    'rw-mutex-review',
    'generics-in-go',
    'constraints',
    'parametric-constraints',
    'wrapping-up',
  ],
  extras: [
    'user-input',
    'standard-library',
    'custom-package',
    'remote-package',
    'clean-package',
    'proverbs',
  ],
};

export const categories = [
  {
    title: 'Intro',
    description:
      'A beginner-friendly introduction to the Go programming language.',
    link: '/intro',
    tags: topics.intro,
  },
  {
    title: 'Setting Up Environment',
    description: 'Learn how to get your Go development environment ready.',
    link: '/setting-up-environment',
    tags: topics.setting_up_environment,
  },
  {
    title: 'Variables and Types',
    description: "Understand Go's data types and how to declare variables.",
    link: '/variables-and-types',
    tags: topics.variables_and_types,
  },
  {
    title: 'Functions',
    description: 'Define reusable blocks of code in Go',
    link: '/functions',
  },
  {
    title: 'Structs',
    description: 'Create custom data structures in Go.',
    link: '/structs',
  },
  {
    title: 'Interfaces',
    description: 'Define contracts for behavior, promoting code flexibility.',
    link: '/interfaces',
  },
  {
    title: 'Errors',
    description: 'Handle errors gracefully in Go.',
    link: '/errors',
  },
  {
    title: 'Loops',
    description:
      'Iterate over sequences of data in Go which is essential for repeating actions',
    link: '/loops',
  },
  {
    title: 'Slices',
    description: 'Dynamic arrays in Go.',
    link: '/slices',
  },
  {
    title: 'Maps',
    description: 'Key-value pairs for efficient data storage.',
    link: '/maps',
  },
  {
    title: 'Advanced Functions',
    description: "Explore Go's more complex function features.",
    link: '/advanced-functions',
  },
  {
    title: 'Channels',
    description: 'Communicate between goroutines safely and concurrently.',
    link: '/channels',
  },
  {
    title: 'Mutexes and Generics',
    description: 'Protect shared data from race conditions.',
    link: '/mutexes-and-generics',
  },
  {
    title: 'Extras',
    description:
      'Additional Go concepts and Go proverbs from creator of Go language.',
    link: '/extras',
  },
];

export const exercises = [
  {
    difficulty: 'Beginner',
    exercises: [
      'Create a program that greets the user based on the time of day (Good morning, Good afternoon, Good evening).',
      'Simulate a dice roll using `rand.Intn()` and print the result.',
      'Ask the user for their favorite programming language and respond differently if it is “Go”.',
      'Convert a distance in kilometers to miles (1 km ≈ 0.621 miles) and print both values.',
      'Create a program that splits a restaurant bill among friends evenly, rounding properly.',
      'Write a program that determines whether a given number is even or odd using conditionals.',
      'Build a small “quote of the day” app that randomly picks from a list of inspirational quotes.',
      'Use a `for` loop to print the multiplication table for a number entered by the user.',
      'Create a slice of grocery items, add a few new items, remove one, and print the updated list.',
      'Write a function that searches for a given city name in a slice of cities and prints whether it was found.',
      'Implement a simple calculator that supports +, -, *, and / operations using user input.',
      'Write a function `reverseString(s string) string` and test it with different inputs.',
      'Create a “guess the number” game where the computer picks a number and the user guesses until correct.',
      'Define a `Person` struct with `Name` and `Age`, and print personalized greetings using it.',
      'Write a recursive function that computes the nth Fibonacci number.',
      'Make a simple to-do list program that lets the user add and display tasks (store them in a slice).',
      'Use a map to associate country names with their capitals and allow the user to look up any capital.',
      'Define an interface `Animal` with a method `Speak()`, and create structs for Dog, Cat, and Cow implementing it.',
    ],
    message:
      'Fun, bite-sized challenges to learn Go basics and logic. Try experimenting with user input, conditionals, loops, and basic data structures. You’ll get a good feel for Go syntax and flow!',
  },
  {
    difficulty: 'Intermediate',
    exercises: [
      'Bank Simulator 2.0: Create a `BankAccount` struct with Deposit, Withdraw, and Transfer methods. Handle overdraft protection gracefully.',
      'Ticket Booking System: Create structs for `Event` and `User`. Let users book, cancel, and view tickets with data validation.',
      'Word Frequency Counter: Read a text file and output the top 5 most common words. Ignore punctuation and case.',
      'Expense Tracker: Read a CSV of expenses, categorize them, and output total spent per category.',
      'Weather CLI App: Fetch live weather data using `net/http` from a public API and display temperature and condition.',
      'Parallel Download Manager: Download multiple files concurrently using goroutines and channels. Track completion order.',
      'JSON Config Loader: Parse a JSON configuration file into structs, validate fields, and print a formatted summary.',
      'Local File Organizer: Write a tool that moves files into folders based on their extension (e.g., .jpg → images).',
      'Matrix Operations: Implement addition, subtraction, and multiplication for 2D slices representing matrices.',
      'Polling App: Create a command-line voting system where users can vote for candidates and display results as text bars.',
      'URL Pinger: Accept a list of URLs and concurrently check which ones are reachable.',
      'CLI Quiz Game: Load questions from a JSON file, quiz the user, and keep score.',
      'Traffic Light Simulation: Use goroutines and channels to simulate a traffic light cycling through states.',
      'Image Downloader: Download images from URLs listed in a file using concurrency.',
      'REST API: Build a small REST API with `net/http` for managing a list of books or tasks. Implement CRUD operations.',
    ],
    message:
      'Intermediate projects are where you start feeling the “Go rhythm.” Work with files, APIs, JSON, concurrency, and build mini real-world utilities. Try packaging your code neatly with structs and methods.',
  },
  {
    difficulty: 'Advanced',
    exercises: [
      'Mini Distributed Cache: Build a distributed in-memory cache using consistent hashing and peer-to-peer communication.',
      'Real-time Chat Server: Implement a WebSocket-based chat app with multiple rooms and connected clients.',
      'Job Queue System: Design a job queue that schedules and processes background jobs using goroutines and worker pools.',
      'Custom ORM Layer: Build a lightweight ORM that translates structs into SQL queries using reflection.',
      'Recommendation Engine: Parse user interaction data and recommend items based on simple collaborative filtering logic.',
      'Stream Processor: Build a system that consumes real-time events from Kafka (or a mock source) and performs aggregations.',
      'JWT-based Auth API: Create a REST API with user registration/login and JWT-based authentication. Add middleware for protection.',
      'GraphQL API: Build a GraphQL API for a social app using `graphql-go`. Implement query resolvers and nested data fetching.',
      'Log Analyzer: Process gigabytes of server logs concurrently and produce insights such as top endpoints and average latency.',
      'Plugin System: Implement a plugin mechanism using Go interfaces and dynamic loading via the `plugin` package.',
      'gRPC Microservice: Build two microservices communicating via gRPC. Define `.proto` files and implement both server and client.',
      'Dependency Injection Framework: Build a simple DI container that injects dependencies into structs automatically.',
      'Custom CLI Tool: Create a command-line tool (like `git` or `kubectl`) that supports multiple subcommands and flags.',
      'Rate Limiter: Implement a token bucket rate limiter and test it under load.',
      'Performance Profiler: Use `pprof` to find bottlenecks in a concurrent program and optimize it.',
      'Key-Value Store on Disk: Implement a persistent key-value store using memory-mapped files or append-only logs.',
      'Build Your Own Scheduler: Simulate a task scheduler that runs tasks at specific intervals using timers and channels.',
      'Tiny Search Engine: Crawl a set of websites and build a basic inverted index for keyword searching.',
      'AI Chatbot Backend: Build a simple chatbot backend that uses pattern matching or Markov chains for responses.',
      'TinyGo IoT Project: Use TinyGo to blink an LED or read a temperature sensor from a microcontroller.',
    ],
    message:
      'These are creative, large-scale projects that stretch your Go mastery — concurrency, distributed systems, real APIs, and architecture patterns. Each one can evolve into a portfolio-worthy project.',
  },
];
